"""create postgresql topology tables

Revision ID: 36296b943ff8
Revises: 
Create Date: 2026-06-06 06:10:39.889115
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '36296b943ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_models',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('manufacturer', sa.Text(), server_default='', nullable=False),
    sa.Column('rack_units', sa.Integer(), server_default='1', nullable=False),
    sa.Column('front_panel_svg', sa.Text(), server_default='', nullable=False),
    sa.Column('back_panel_svg', sa.Text(), server_default='', nullable=False),
    sa.Column('port_layout', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('projects',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), server_default='', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role in ('manager', 'editor', 'viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('buildings',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_id', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('project_uid', 'building_id', name='uq_buildings_project_building_id')
    )
    op.create_table('device_variants',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=True),
    sa.Column('device_model_uid', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('variant', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_model_uid'], ['device_models.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_device_variants_project_model', 'device_variants', ['project_uid', 'device_model_uid'], unique=False)
    op.create_table('operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_uid', sa.Text(), nullable=False),
    sa.Column('operation_type', sa.Text(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('user_uid', sa.Text(), nullable=True),
    sa.Column('user_role', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_log_entity_id', 'operation_log', ['entity_type', 'entity_uid', 'id'], unique=False)
    op.create_index('ix_operation_log_project_id', 'operation_log', ['project_uid', 'id'], unique=False)
    op.create_index('ix_operation_log_user_id', 'operation_log', ['user_uid', 'id'], unique=False)
    op.create_table('pending_changes',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('requested_by_user_uid', sa.Text(), nullable=False),
    sa.Column('reviewed_by_user_uid', sa.Text(), nullable=True),
    sa.Column('target_entity_type', sa.Text(), nullable=False),
    sa.Column('target_entity_uid', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('review_note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_pending_changes_status_created', 'pending_changes', ['status', 'created_at'], unique=False)
    op.create_index('ix_pending_changes_target', 'pending_changes', ['target_entity_type', 'target_entity_uid'], unique=False)
    op.create_table('source_imports',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), server_default='', nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('validation_findings',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=True),
    sa.Column('finding_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), server_default='', nullable=False),
    sa.Column('entity_type', sa.Text(), server_default='', nullable=False),
    sa.Column('entity_uid', sa.Text(), server_default='', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_validation_findings_entity', 'validation_findings', ['entity_type', 'entity_uid'], unique=False)
    op.create_index('ix_validation_findings_project_type', 'validation_findings', ['project_uid', 'finding_type'], unique=False)
    op.create_table('rooms',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('room_type', sa.Text(), server_default='data_hall', nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('construction_phase', sa.Text(), server_default='Management & Ethernet', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('building_uid', 'room_id', name='uq_rooms_building_room_id')
    )
    op.create_index('ix_rooms_scope', 'rooms', ['project_uid', 'building_uid', 'room_id'], unique=False)
    op.create_table('cabinets',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_uid', sa.Text(), nullable=False),
    sa.Column('cabinet_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), server_default='', nullable=False),
    sa.Column('cabinet_group', sa.Text(), server_default='', nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='not_installed', nullable=False),
    sa.Column('construction_phase', sa.Text(), server_default='Management & Ethernet', nullable=False),
    sa.Column('max_rack_unit', sa.Integer(), server_default='48', nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('source_col', sa.Integer(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('room_uid', 'cabinet_id', name='uq_cabinets_room_cabinet_id')
    )
    op.create_index('ix_cabinets_room_layout', 'cabinets', ['room_uid', 'source_row', 'source_col'], unique=False)
    op.create_table('ladder_rack_junctions',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_uid', sa.Text(), nullable=True),
    sa.Column('junction_id', sa.Text(), nullable=False),
    sa.Column('junction_type', sa.Text(), server_default='', nullable=False),
    sa.Column('point', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('width', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('height', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('height_tier', sa.Text(), server_default='', nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('construction_phase', sa.Text(), server_default='Management & Ethernet', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_ladder_rack_junctions_room', 'ladder_rack_junctions', ['room_uid'], unique=False)
    op.create_index('ix_ladder_rack_junctions_scope', 'ladder_rack_junctions', ['project_uid', 'building_uid', 'junction_id'], unique=False)
    op.create_table('devices',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_uid', sa.Text(), nullable=False),
    sa.Column('cabinet_uid', sa.Text(), nullable=False),
    sa.Column('rack_unit', sa.Integer(), nullable=False),
    sa.Column('device_model_uid', sa.Text(), nullable=True),
    sa.Column('device_variant_uid', sa.Text(), nullable=True),
    sa.Column('device_model_name', sa.Text(), server_default='', nullable=False),
    sa.Column('rack_units', sa.Integer(), server_default='1', nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='not_installed', nullable=False),
    sa.Column('construction_phase', sa.Text(), server_default='Management & Ethernet', nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('model_aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('port_layout_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['cabinet_uid'], ['cabinets.uid'], ),
    sa.ForeignKeyConstraint(['device_model_uid'], ['device_models.uid'], ),
    sa.ForeignKeyConstraint(['device_variant_uid'], ['device_variants.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('cabinet_uid', 'rack_unit', name='uq_devices_cabinet_rack_unit')
    )
    op.create_index('ix_devices_room', 'devices', ['room_uid'], unique=False)
    op.create_table('ladder_rack_segments',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_uid', sa.Text(), nullable=True),
    sa.Column('segment_id', sa.Text(), nullable=False),
    sa.Column('polyline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('design_length_meters', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('actual_length_meters', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('width', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('height', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('height_tier', sa.Text(), server_default='', nullable=False),
    sa.Column('junction_a_uid', sa.Text(), nullable=False),
    sa.Column('junction_z_uid', sa.Text(), nullable=False),
    sa.Column('lifecycle_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('construction_phase', sa.Text(), server_default='Management & Ethernet', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('actual_length_meters is null or actual_length_meters >= 0', name='ck_ladder_rack_segments_actual_length_non_negative'),
    sa.CheckConstraint('design_length_meters is null or design_length_meters >= 0', name='ck_ladder_rack_segments_design_length_non_negative'),
    sa.CheckConstraint('junction_a_uid <> junction_z_uid', name='ck_ladder_rack_segments_distinct_junctions'),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['junction_a_uid'], ['ladder_rack_junctions.uid'], ),
    sa.ForeignKeyConstraint(['junction_z_uid'], ['ladder_rack_junctions.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_ladder_rack_segments_junction_a', 'ladder_rack_segments', ['junction_a_uid'], unique=False)
    op.create_index('ix_ladder_rack_segments_junction_z', 'ladder_rack_segments', ['junction_z_uid'], unique=False)
    op.create_index('ix_ladder_rack_segments_room', 'ladder_rack_segments', ['room_uid'], unique=False)
    op.create_index('ix_ladder_rack_segments_scope', 'ladder_rack_segments', ['project_uid', 'building_uid', 'segment_id'], unique=False)
    op.create_table('cable_bundles',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('scoped_uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_uid', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('primary_ladder_rack_segment_uid', sa.Text(), nullable=True),
    sa.Column('lifecycle_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('construction_phase', sa.Text(), server_default='Management & Ethernet', nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['primary_ladder_rack_segment_uid'], ['ladder_rack_segments.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('scoped_uid', name='uq_cable_bundles_scoped_uid')
    )
    op.create_index('ix_cable_bundles_primary_segment', 'cable_bundles', ['primary_ladder_rack_segment_uid'], unique=False)
    op.create_index('ix_cable_bundles_room', 'cable_bundles', ['room_uid'], unique=False)
    op.create_table('ports',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_uid', sa.Text(), nullable=False),
    sa.Column('cabinet_uid', sa.Text(), nullable=False),
    sa.Column('device_uid', sa.Text(), nullable=True),
    sa.Column('port_name', sa.Text(), nullable=False),
    sa.Column('connector_type', sa.Text(), server_default='other', nullable=False),
    sa.Column('side', sa.Text(), server_default='', nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['cabinet_uid'], ['cabinets.uid'], ),
    sa.ForeignKeyConstraint(['device_uid'], ['devices.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_ports_cabinet', 'ports', ['cabinet_uid'], unique=False)
    op.create_index('ix_ports_device_port_name', 'ports', ['device_uid', 'port_name'], unique=False)
    op.create_index('ix_ports_room', 'ports', ['room_uid'], unique=False)
    op.create_table('cable_bundle_ladder_rack_segments',
    sa.Column('cable_bundle_uid', sa.Text(), nullable=False),
    sa.Column('ladder_rack_segment_uid', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cable_bundle_uid'], ['cable_bundles.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ladder_rack_segment_uid'], ['ladder_rack_segments.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cable_bundle_uid', 'ladder_rack_segment_uid')
    )
    op.create_index('ix_cable_bundle_ladder_rack_segments_segment', 'cable_bundle_ladder_rack_segments', ['ladder_rack_segment_uid'], unique=False)
    op.create_table('cables',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('project_uid', sa.Text(), nullable=False),
    sa.Column('building_uid', sa.Text(), nullable=False),
    sa.Column('room_uid', sa.Text(), nullable=True),
    sa.Column('a_port_uid', sa.Text(), nullable=False),
    sa.Column('z_port_uid', sa.Text(), nullable=False),
    sa.Column('cable_type', sa.Text(), nullable=False),
    sa.Column('cable_group', sa.Text(), server_default='', nullable=False),
    sa.Column('import_status', sa.Text(), server_default='', nullable=False),
    sa.Column('construction_phase', sa.Text(), server_default='Management & Ethernet', nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('current_phase', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('designed_length_meters', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('length_used_meters', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('a_optic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('z_optic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['a_port_uid'], ['ports.uid'], ),
    sa.ForeignKeyConstraint(['building_uid'], ['buildings.uid'], ),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.ForeignKeyConstraint(['z_port_uid'], ['ports.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_cables_a_port', 'cables', ['a_port_uid'], unique=False)
    op.create_index('ix_cables_building_import_status', 'cables', ['building_uid', 'import_status'], unique=False)
    op.create_index('ix_cables_project_phase', 'cables', ['project_uid', 'construction_phase'], unique=False)
    op.create_index('ix_cables_z_port', 'cables', ['z_port_uid'], unique=False)
    op.create_table('cable_bundle_cables',
    sa.Column('cable_bundle_uid', sa.Text(), nullable=False),
    sa.Column('cable_uid', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cable_bundle_uid'], ['cable_bundles.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cable_uid'], ['cables.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cable_bundle_uid', 'cable_uid')
    )
    op.create_index('ix_cable_bundle_cables_cable', 'cable_bundle_cables', ['cable_uid'], unique=False)
    op.create_table('source_cable_rows',
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('source_import_uid', sa.Text(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cable_uid', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cable_uid'], ['cables.uid'], ),
    sa.ForeignKeyConstraint(['source_import_uid'], ['source_imports.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_source_cable_rows_import_row', 'source_cable_rows', ['source_import_uid', 'row_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_cable_rows_import_row', table_name='source_cable_rows')
    op.drop_table('source_cable_rows')
    op.drop_index('ix_cable_bundle_cables_cable', table_name='cable_bundle_cables')
    op.drop_table('cable_bundle_cables')
    op.drop_index('ix_cables_z_port', table_name='cables')
    op.drop_index('ix_cables_project_phase', table_name='cables')
    op.drop_index('ix_cables_building_import_status', table_name='cables')
    op.drop_index('ix_cables_a_port', table_name='cables')
    op.drop_table('cables')
    op.drop_index('ix_cable_bundle_ladder_rack_segments_segment', table_name='cable_bundle_ladder_rack_segments')
    op.drop_table('cable_bundle_ladder_rack_segments')
    op.drop_index('ix_ports_room', table_name='ports')
    op.drop_index('ix_ports_device_port_name', table_name='ports')
    op.drop_index('ix_ports_cabinet', table_name='ports')
    op.drop_table('ports')
    op.drop_index('ix_cable_bundles_room', table_name='cable_bundles')
    op.drop_index('ix_cable_bundles_primary_segment', table_name='cable_bundles')
    op.drop_table('cable_bundles')
    op.drop_index('ix_ladder_rack_segments_scope', table_name='ladder_rack_segments')
    op.drop_index('ix_ladder_rack_segments_room', table_name='ladder_rack_segments')
    op.drop_index('ix_ladder_rack_segments_junction_z', table_name='ladder_rack_segments')
    op.drop_index('ix_ladder_rack_segments_junction_a', table_name='ladder_rack_segments')
    op.drop_table('ladder_rack_segments')
    op.drop_index('ix_devices_room', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_ladder_rack_junctions_scope', table_name='ladder_rack_junctions')
    op.drop_index('ix_ladder_rack_junctions_room', table_name='ladder_rack_junctions')
    op.drop_table('ladder_rack_junctions')
    op.drop_index('ix_cabinets_room_layout', table_name='cabinets')
    op.drop_table('cabinets')
    op.drop_index('ix_rooms_scope', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_validation_findings_project_type', table_name='validation_findings')
    op.drop_index('ix_validation_findings_entity', table_name='validation_findings')
    op.drop_table('validation_findings')
    op.drop_table('source_imports')
    op.drop_index('ix_pending_changes_target', table_name='pending_changes')
    op.drop_index('ix_pending_changes_status_created', table_name='pending_changes')
    op.drop_table('pending_changes')
    op.drop_index('ix_operation_log_user_id', table_name='operation_log')
    op.drop_index('ix_operation_log_project_id', table_name='operation_log')
    op.drop_index('ix_operation_log_entity_id', table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index('ix_device_variants_project_model', table_name='device_variants')
    op.drop_table('device_variants')
    op.drop_table('buildings')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('device_models')
    # ### end Alembic commands ###
